
query TopicOfTheDay($date: Datetime) {
  allTopics(first:1, orderBy: TOPICOFARTICLES_BY_TOPIC_ID__COUNT_DESC) {
    nodes {
      id
      name
      topicofarticlesByTopicId(filter: { 
  	    articleByArticleId: {
					and: [
            { 
              publicationDate: {
                equalTo: $date,
                isNull: false
              }
            },
            
          ]
        }
      }) {
        totalCount 
      }
    }
  }
}